language: perl
perl:
  - "5.14"
  - "5.12"
before_install:
  - "cpanm --notest Dist::Zilla"
  - "cpanm --notest Dist::Zilla::PluginBundle::Author::MELO"
  - "git config --global github.user melo"
install: "dzil authordeps | xargs cpanm --notest && dzil listdeps | xargs cpanm --notest"
script: "dzil test --release"
